Upgrade for Sylius 1.11 and drop support for Sylius 1.9, 1.10 and PHP 7.4
webgriffe/WebgriffeSyliusTableRateShippingPlugin pull request #16
Opened 2022-04-07 14:53 UTC by lruozzi9

2022-04-07 16:15 UTC, LucaGallinari requested changes

2022-04-07 16:15 UTC, LucaGallinari commented on src/DependencyInjection/Configuration.php
> +        $treeBuilder = new TreeBuilder('webgriffe_sylius_table_rate_shipping_plugin');
```suggestion
        $treeBuilder = new TreeBuilder('webgriffe_sylius_table_rate_shipping');
```
If i remember correctly you must not put the "_plugin" suffix here otherwise it will fail to load the configs.

2022-04-08 07:08 UTC, lruozzi9 commented on src/DependencyInjection/Configuration.php
> +        $treeBuilder = new TreeBuilder('webgriffe_sylius_table_rate_shipping_plugin');
That's not completely true.. This string is not the same one used to read the configuration in your application, it is more like a "title". Check [here](https://github.com/webgriffe/SyliusActiveCampaignPlugin/blob/0968216a5045467da7416ac57b149355aa56413d/src/DependencyInjection/Configuration.php#L21) and [here](https://github.com/webgriffe/SyliusActiveCampaignPlugin/blob/0968216a5045467da7416ac57b149355aa56413d/tests/Application/config/packages/webgriffe_sylius_active_campaign_plugin.yaml#L4) for example..

2022-04-08 07:59 UTC, LucaGallinari commented on src/DependencyInjection/Configuration.php
> +        $treeBuilder = new TreeBuilder('webgriffe_sylius_table_rate_shipping_plugin');
Ok, true!

2022-04-08 08:00 UTC, LucaGallinari approved these changes

2022-04-08 08:00 UTC, merged